apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
data:
  mapUsers: |
    {{- range $.Values.users }}
    {{- if .admin }}
    - groups:
      - system:masters
      userarn: arn:aws:iam::{{ $.Values.awsAccountId }}:user/{{ .username }}
      username: {{ .username }}
    {{- end }}
    {{- end }}
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::{{ .Values.awsAccountId }}:role/eks-node-group-role
      username: system:node:{{ `{{EC2PrivateDNSName}}` }}